import org.w3c.dom.ls.LSOutput;

public class Main {
    public static void main(String[] args) {
        int i = 32131;
        byte b = 100;
        short s = 32000;
        long l = 9232323232L;
        float f = 3.6f;
        double d = 763789.123123;
        System.out.println();
        System.out.println("Задача 1:");
        System.out.println("Значение переменной i с типом int равно " + i);
        System.out.println("Значение переменной b с типом byte равно " + b);
        System.out.println("Значение переменной s с типом short равно " + s);
        System.out.println("Значение переменной l с типом long равно " + l);
        System.out.println("Значение переменной f с типом float равно " + f);
        System.out.println("Значение переменной d с типом double равно " + d);
        System.out.println();
        System.out.println("Задача 2:");
        float flo = 27.12f;
        long lon = 987678965549L;
        float floTwo = 2.786f;
        short shor = 569;
        short shortTwo = -159;
        short shortThree = 27897;
        byte byt = 97;
        System.out.println();
        System.out.println("Задача 3:");
        var lyudPav = 23;
        var annSerg = 27;
        var ekatAnd = 30;
        var allSheets = 480;
        var allStudents = lyudPav + annSerg + ekatAnd;
        var allSheetsPerStudents = allSheets / allStudents;
        System.out.println("На каждого ученика рассчитано " + allSheetsPerStudents + " листов бумаги");
        System.out.println();
        System.out.println("Задача 4:");
        var performance = 16;
        var perfPerTwoMinutes = 2;
        var perfPerOneMinutes = performance / perfPerTwoMinutes; //производительность за 1 минуту
        var perfPerTwentyMinutes = perfPerOneMinutes * 20;
        var perfPerOneDay = perfPerOneMinutes * 1440;
        var perfPerThreeDay = perfPerOneMinutes * 1440 * 3;
        var perfPerOneMonth = perfPerOneMinutes * 1440 * 31;
        System.out.println("За 20 минут машина произвела " + perfPerTwentyMinutes + " штук бутылок");
        System.out.println("За 1 день машина произвела " + perfPerOneDay + " штук бутылок");
        System.out.println("За 3 дня машина произвела " + perfPerThreeDay + " штук бутылок");
        System.out.println("За 1 месяц машина произвела " + perfPerOneMonth + " штук бутылок");
        System.out.println();
        System.out.println("Задача 5:");
        var allForOverhaul = 120;
        var colorWhitePerOneClass = 2;
        var colorBrownPerOneClass = 4;
        var allClassSchool = allForOverhaul / (colorWhitePerOneClass + colorBrownPerOneClass);
        var oneClassWhiteColor = allClassSchool * colorWhitePerOneClass;
        var oneClassBrownColor = allClassSchool * colorBrownPerOneClass;
        System.out.println("В школе, где " + allClassSchool + " классов, нужно " + oneClassWhiteColor + " банок белой краски и " + oneClassBrownColor + " банок коричневой краски");
        System.out.println();
        System.out.println("Задача 6:");
        var banana = 5;
        var bananaWeight = 5 * 80;
        var milk = 200;
        var milkWeigh = (200 / 2) * 105;
        var icecream = 2;
        var icecreamWeight = 2 * 100;
        var egg = 4;
        var eggWeight = 4 * 70;
        var breakfastWeightGramm = bananaWeight + milkWeigh + icecreamWeight + eggWeight;
        var breakfastWeightKilo = breakfastWeightGramm / 1000;
        System.out.println(breakfastWeightGramm + " г");
        System.out.println(breakfastWeightKilo + " кг");
        System.out.println();
        System.out.println("Задача 7:");
        var grossWeight = 7000;
        var grossPerDayOneVar = 250;
        var grossPerDayTwoVar = 500;
        var grossWeightOneVar = grossWeight / grossPerDayOneVar;
        var grossWeightTwoVar = grossWeight / grossPerDayTwoVar;
        var grossWeightVarAverage = (grossWeightTwoVar + grossWeightOneVar) / 2;
        System.out.println(grossWeightOneVar);
        System.out.println(grossWeightTwoVar);
        System.out.println(grossWeightVarAverage);
        System.out.println();
        System.out.println("Задача 8:");
        var masha = 67760;
        var denis = 83690;
        var kristina = 76230;
        var grossMasha = (masha / 100) * 10 + masha;
        var grossDenis = (denis / 100) * 10 + denis;
        var grossKristina = (kristina / 100) * 10 + kristina;
        var diffMasha = (grossMasha - masha) * 12;
        var diffDenis = (grossDenis - denis) * 12;
        var diffKristina = (grossKristina - kristina) * 12;
        System.out.println("Маша теперь получает " + grossMasha + " рублей. Годовой доход вырос на " + diffMasha + " рублей");
        System.out.println("Денис теперь получает " + grossDenis + " рублей. Годовой доход вырос на " + diffDenis + " рублей");
        System.out.println("Маша теперь получает " + grossKristina + " рублей. Годовой доход вырос на " + diffKristina + " рублей");
    }


}
